Repository bazelbuild/rules_apple, pull requests merged in 2019-07, with the labels that each got.

#485 Document the tvos_unit_test and tvos_ui_test rules.
  doc/README.md
  doc/rules-tvos.md
Labels: cla: no

#487 Fix minor spelling and formatting issue
  doc/common_info.md
Labels: cla: no

#488 Add a small description on where to find runfiles resources for tests.
  doc/common_info.md
Labels: cla: yes

#489 Add infrastructure to selectively add rule class transitions to rule_descriptors.
  apple/internal/rule_factory.bzl
  apple/internal/rule_support.bzl
  apple/internal/transition_support.bzl
Labels: cla: yes

#486 Handle ambiguous signer in codesigningtool.py
  apple/internal/rule_support.bzl
Labels: Import Ready, cla: yes

#500 Disable `print` buildifier check
  .bazelci/presubmit.yml
Labels: cla: yes

#498 Minor refactor to the Apple rule transition.
  apple/internal/transition_support.bzl
Labels: cla: yes

#496 Update xctestrunner
  apple/repositories.bzl
Labels: Import Ready, cla: yes

#501 Simplify the globs that are matching everything in a directory.
  examples/resources/BUILD
  test/ios_application_resources_test.sh
  test/macos_application_resources_test.sh
  test/macos_application_test.sh
  test/macos_bundle_test.sh
Labels: cla: yes

#502 Fix issue when depending on a rule that propagates AppleResourceInfo from an apple_resource_bundle target.
  apple/internal/resources.bzl
  test/ios_application_resources_test.sh
Labels: cla: yes

#503 Rewrite resource owner tracking to avoid quadratic blowup
  apple/internal/partials/resources.bzl
  apple/internal/resource_rules/apple_resource_bundle.bzl
  apple/internal/resources.bzl
  apple/providers.bzl
  test/ios_application_resources_test.sh
Labels: cla: no

#494 Add flag to strip extra locales.
  apple/internal/partials/resources.bzl
  apple/internal/processor.bzl
  apple/internal/rule_support.bzl
  apple/internal/utils/bundle_paths.bzl
  doc/common_info.md
  test/ios_application_resources_test.sh
  test/macos_application_resources_test.sh
  test/testdata/resources/fr.lproj/localized.plist
  test/testdata/resources/fr.lproj/localized.strings
  test/testdata/resources/fr.lproj/localized.txt
  test/testdata/resources/fr.lproj/storyboard_ios.storyboard
  test/testdata/resources/fr.lproj/view_ios.xib
  test/testdata/resources/settings_ios.bundle/Base.lproj/Root.strings
  test/testdata/resources/settings_ios.bundle/fr.lproj/Root.strings
Labels: cla: no

#506 Update parameters to match format used elsewhere in file.
  doc/common_info.md
Labels: cla: no

#507 Add John and Gabe to contributors
  CONTRIBUTORS
Labels: cla: yes

#505 Add support for ios_unit_test and ios_ui_test for depending on ios_framework targets.
  apple/internal/testing/apple_test_bundle_support.bzl
  apple/ios.bzl
  doc/rules-ios.md
  test/ios_ui_test_test.sh
  test/ios_unit_test_test.sh
Labels: cla: yes

#510 Add additional_contents to macos_unit_tests and macos_ui_test
  apple/internal/testing/apple_test_bundle_support.bzl
  doc/rules-macos.md
  test/macos_ui_test_test.sh
  test/macos_unit_test_test.sh
Labels: cla: yes

#517 Disable ButtonsMacTest since there is something borked on BuildKite
  examples/multi_platform/Buttons/BUILD
Labels: cla: yes

#513 Enable rule transitions for watchOS targets.
  apple/internal/rule_support.bzl
  apple/internal/transition_support.bzl
Labels: cla: yes
