Repository bazelbuild/rules_apple, pull requests merged in 2019-09, with the labels that each got.

#572 Pass is_test to swift_runtime_linkopts
  apple/internal/binary_support.bzl
  apple/internal/swift_support.bzl
  apple/internal/testing/apple_test_assembler.bzl
Labels: Import Ready, cla: yes

#574 Migrates integration tests to use test-bin instead of test-genfiles.
  test/apple_shell_testutils.sh
  test/dtrace_test.sh
  test/ios_application_resources_test.sh
  test/ios_application_test.sh
  test/ios_framework_test.sh
  test/ios_ui_test_test.sh
  test/ios_unit_test_test.sh
  test/macos_application_resources_test.sh
  test/macos_ui_test_test.sh
  test/macos_unit_test_test.sh
  test/tvos_framework_test.sh
  test/tvos_ui_test_test.sh
  test/tvos_unit_test_test.sh
  test/watchos_application_test.sh
Labels: cla: yes

#575 Stop packaging Swift stdlib dylibs if the minimum OS version for the bundle is greater than the version after which Swift is packaged into the OS.
  apple/internal/partials/swift_dylibs.bzl
Labels: cla: yes

#576 Minor bug fixes.
  apple/internal/testing/apple_test_rule_support.bzl
Labels: cla: yes

#577 Bump tag in README.md to latest version (0.18.0)
  README.md
Labels: cla: yes

#579 Remove unused variable.
  apple/internal/testing/apple_test_assembler.bzl
Labels: cla: yes

#582 Allow setting compiler optimization
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/rules/apple_verification_test.bzl
Labels: cla: yes

#583 Add ios_extension example to the Buttons project.
  examples/multi_platform/Buttons/BUILD
  examples/multi_platform/Buttons/ButtonsExtension/ActionRequestHandler.swift
  examples/multi_platform/Buttons/ButtonsExtension/Info.plist
Labels: cla: yes

#584 Fixes issue where some arch slices of Swift dylibs were being stripped incorrectly.
  tools/swift_stdlib_tool/swift_stdlib_tool.sh
Labels: cla: yes

#540 Add analysis test rule for checking for outputs of an action.
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/rules/analysis_target_outputs_test.bzl
Labels: cla: yes

#587 Disable bzl-visibility since it's not ready to be used.
  .bazelci/presubmit.yml
Labels: cla: yes

#590 Apease the export gods
  apple/testing/default_runner/BUILD
Labels: cla: yes

#588 Add plist value checking to archive_contents_test()
  test/starlark_tests/ios_unit_test_tests.bzl
  test/starlark_tests/macos_bundle_tests.bzl
  test/starlark_tests/macos_quick_look_plugin_tests.bzl
  test/starlark_tests/macos_ui_test_tests.bzl
  test/starlark_tests/macos_unit_test_tests.bzl
  test/starlark_tests/rules/common_verification_tests.bzl
  test/starlark_tests/verifier_scripts/archive_contents_test.sh
Labels: cla: yes

#585 Fixes swift dylibs issue moving around in Xcode 11.
  apple/internal/partials/swift_dylibs.bzl
  tools/swift_stdlib_tool/swift_stdlib_tool.sh
Labels: cla: yes

#591 Add asset catalog testing
  test/starlark_tests/rules/common_verification_tests.bzl
  test/starlark_tests/verifier_scripts/archive_contents_test.sh
Labels: cla: yes

#593 Pass is_test = True for testonly binaries
  apple/internal/binary_support.bzl
Labels: Import Ready, cla: yes

#594 Rollback of commit 9348eec8b70417b7255a45353388da92132e3559
  apple/internal/binary_support.bzl
Labels: cla: no

#586 Append when redirecting to $TEST_log
  test/apple_shell_testutils.sh
  test/bazel_testrunner.sh
Labels: Import Ready, cla: yes

#609 Make grep-includes available to apple starlark build rules
  apple/internal/rule_factory.bzl
Labels: cla: no

#610 Fix code format not display correctly
  doc/rules-ios.md
Labels: Import Ready, cla: yes

#611 Update documentation to sync with minimum_os_version being a required attribute.
  doc/rules-ios.md
  doc/rules-macos.md
  doc/rules-tvos.md
  doc/rules-watchos.md
Labels: cla: yes

#612 Add documentation on bundle size limits.
  doc/common_info.md
Labels: cla: yes

#613 Update get-task-allow entitlement
  apple/internal/entitlement_rules.bzl
  doc/common_info.md
  test/ios_application_test.sh
  test/testdata/provisioning/integration_testing_ios.mobileprovision
  test/testdata/provisioning/integration_testing_tvos.mobileprovision
Labels: Import Ready, cla: yes

#614 Rollback of commit 0d18971fb383f85ea1e844766aca24e39fa4163b
  apple/internal/entitlement_rules.bzl
  doc/common_info.md
  test/ios_application_test.sh
  test/testdata/provisioning/integration_testing_ios.mobileprovision
  test/testdata/provisioning/integration_testing_tvos.mobileprovision
Labels: cla: yes

#615 Drop the shard count now that more tests were moved out.
  test/BUILD
Labels: cla: yes

#597 Pass is_test = True for testonly binaries
  apple/internal/binary_support.bzl
Labels: Import Ready, cla: yes

#616 Migrate remaining macOS rules to rules instead of macros.
  apple/internal/macos_rules.bzl
  apple/internal/rule_support.bzl
  apple/macos.bzl
Labels: cla: yes
