Repository bazelbuild/rules_apple, pull requests merged in 2019-06, with the labels that each got.

#458 Add a stopgap to green up head bazel builds.
  .bazelci/presubmit.yml
Labels: cla: yes

#459 Depend on rules_swift 0.11.1.
  apple/repositories.bzl
Labels: cla: yes

#460 Second part of a stopgap to green up head bazel builds.
  test/apple_shell_testutils.sh
Labels: cla: yes

#462 Use `to_list()` when iterating over a depset.
  apple/internal/partials/macos_additional_contents.bzl
Labels: cla: yes

#461 Tweak to avoid error from --incompatible_depset_is_not_iterable=false.
  apple/internal/partials/static_framework_header_modulemap.bzl
Labels: cla: yes

#463 Bring ios_test_runner_ui_test inline with ios_test_runner_unit_test
  test/ios_test_runner_ui_test.sh
Labels: cla: yes

#464 Refactor resource rules to independent bzl files.
  apple/internal/BUILD
  apple/internal/resource_rules.bzl
  apple/internal/resource_rules/BUILD
  apple/internal/resource_rules/apple_bundle_import.bzl
  apple/internal/resource_rules/apple_core_ml_library.bzl
  apple/internal/resource_rules/apple_resource_bundle.bzl
  apple/internal/resource_rules/apple_resource_group.bzl
  apple/resources.bzl
Labels: cla: yes

#465 Annotate the unused variable to avoid warnings.
  test/starlark_tests/resources/shared.m
Labels: cla: yes

#467 Use -e _WKExtensionMain linkops for watchos_extension.
  apple/internal/watchos_rules.bzl
Labels: cla: yes

#469 Move the stopgap for python issues.
  .bazelci/presubmit.yml
  .bazelrc
Labels: cla: yes

#471 Python 2 and 3 tweaks.
  tools/bundletool/BUILD
  tools/bundletool/bundletool.py
  tools/bundletool/bundletool_experimental.py
  tools/bundletool/bundletool_unittest.py
  tools/clangrttool/BUILD
  tools/clangrttool/clangrttool.py
  tools/codesigningtool/BUILD
  tools/codesigningtool/codesigningtool.py
  tools/plisttool/BUILD
  tools/plisttool/plisttool.py
  tools/plisttool/plisttool_unittest.py
  tools/provisioning_profile_tool/BUILD
  tools/provisioning_profile_tool/provisioning_profile_tool.py
  tools/py2and3_test.bzl
  tools/versiontool/BUILD
  tools/versiontool/versiontool.py
  tools/versiontool/versiontool_unittest.py
  tools/wrapper_common/BUILD
  tools/wrapper_common/execute.py
  tools/wrapper_common/execute_test.py
  tools/xctoolrunner/BUILD
  tools/xctoolrunner/xctoolrunner.py
  tools/xctoolrunner/xctoolrunner_test.py
Labels: cla: yes

#470 Use yaml anchors, aliases, and merge to avoid repetition.
  .bazelci/presubmit.yml
Labels: cla: yes

#473 Use splitlines over explicit split.
  tools/codesigningtool/codesigningtool.py
Labels: cla: yes

#474 Add utf8 decode to better support py2 and py3.
  tools/codesigningtool/codesigningtool.py
Labels: cla: yes

#472 Remove use of --host_force_python
  .bazelrc
  test/apple_shell_testutils.sh
Labels: cla: yes

#477 Remove usage of split_attr since it has been disabled until correctness issues are fixed.
  test/starlark_tests/rules/apple_verification_test.bzl
Labels: cla: yes

#476 Update tests.
  test/apple_shell_testutils.sh
  test/ios_application_resources_test.sh
  test/ios_application_test.sh
  test/ios_extension_test.sh
  test/ios_framework_test.sh
  test/ios_ui_test_test.sh
  test/ios_unit_test_test.sh
  test/macos_application_resources_test.sh
  test/macos_ui_test_test.sh
  test/macos_unit_test_test.sh
  test/smart_resource_deduplication_test.sh
  test/tvos_framework_test.sh
  test/tvos_ui_test_test.sh
  test/tvos_unit_test_test.sh
Labels: cla: yes

#478 Reverting dSYM tests blacklist. Transitions will not be available soon, so we might as well keep the tests as is.
  test/ios_extension_test.sh
Labels: cla: yes

#479 Fix framework imports with Swift modules
  apple/internal/apple_framework_import.bzl
Labels: Import Ready, cla: yes

#480 Implement _merge_providers() more efficiently by not using intermediate
  apple/internal/resources.bzl
Labels: cla: no
