Repository bazelbuild/rules_apple, pull requests merged in 2019-08, with the labels that each got.

#519 Use plistlib.dump over plistlib.writePlist.
  tools/plisttool/plisttool.py
  tools/provisioning_profile_tool/provisioning_profile_tool.py
Labels: cla: yes

#520 Bump apple_support to 0.7.0.
  apple/repositories.bzl
Labels: cla: yes

#521 Update Skylib and rules_swift dependencies.
  apple/repositories.bzl
Labels: cla: yes

#525 Fix inconsistent documentation.
  doc/rules-ios.md
Labels: cla: yes

#527 Use grep instead of -arch for looking up architecture UUIDS with dwarfdump, since -arch may make dwarfdump return incorrect/empty results.
  test/apple_shell_testutils.sh
Labels: cla: yes

#526 Explain ios_*_test_suite rules more plainly in the documentation.
  doc/rules-ios.md
Labels: cla: yes

#528 Allow environmental variables to be passed into apple_verification_test.
  test/starlark_tests/rules/apple_verification_test.bzl
  test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template
Labels: cla: yes

#514 Adding a field to the ios_application target to allow resources not associated with an objc_library to be included in the resulting application bundle.
  apple/internal/ios_rules.bzl
  apple/internal/macos_rules.bzl
  apple/internal/partials/resources.bzl
  apple/internal/rule_factory.bzl
  apple/internal/testing/apple_test_bundle_support.bzl
  apple/internal/tvos_rules.bzl
  apple/internal/watchos_rules.bzl
  doc/rules-ios.md
  doc/rules-macos.md
  doc/rules-tvos.md
  doc/rules-watchos.md
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/ios_unit_test_tests.bzl
  test/starlark_tests/macos_application_tests.bzl
  test/starlark_tests/resources/BUILD
  test/starlark_tests/targets_under_test/ios/BUILD
  test/starlark_tests/targets_under_test/macos/BUILD
  test/starlark_tests/targets_under_test/tvos/BUILD
  test/starlark_tests/targets_under_test/watchos/BUILD
  test/starlark_tests/tvos_application_tests.bzl
  test/starlark_tests/verifier_scripts/resources_verifier.sh
  test/starlark_tests/watchos_application_tests.bzl
Labels: cla: yes

#529 Add a failure test rule for Skylark tests.
  test/starlark_tests/rules/analysis_failure_message_test.bzl
Labels: cla: yes

#531 Bump skylib to 0.9.0
  apple/repositories.bzl
Labels: cla: yes

#532 Bump apple_support to 0.7.1
  apple/repositories.bzl
Labels: cla: yes

#533 Initialize Skylib in the WORKSPACE so that the unittest framework can be used.
  WORKSPACE
Labels: cla: yes

#534 Bump rules_swift version.
  apple/repositories.bzl
Labels: cla: yes

#512 Removing new_objc_provider from the apple_bundle_import implementation.
  apple/internal/resource_rules/apple_bundle_import.bzl
Labels: cla: yes

#535 Ensuring the absolute path is used for actool actions.
  apple/internal/resource_actions/actool.bzl
Labels: cla: yes

#530 Move apple version tests to Skylark where possible.
  test/apple_bundle_version_test.sh
  test/starlark_tests/BUILD
  test/starlark_tests/apple_bundle_version_tests.bzl
  test/starlark_tests/targets_under_test/apple/BUILD
Labels: cla: yes

#537 Clean up all usages of binary_tags, since they no longer serve any purpose.
  apple/ios.bzl
  apple/macos.bzl
  apple/tvos.bzl
Labels: cla: yes

#538 Enable rule transitions for tvOS rules.
  apple/internal/rule_support.bzl
Labels: cla: yes

#542 Split test rules into a bundle rule and a test rule.
  apple/internal/rule_factory.bzl
  apple/internal/testing/apple_test_assembler.bzl
  apple/internal/testing/apple_test_bundle_support.bzl
  apple/internal/testing/apple_test_rule_support.bzl
  apple/internal/testing/ios_rules.bzl
  apple/internal/testing/macos_rules.bzl
  apple/internal/testing/tvos_rules.bzl
  apple/ios.bzl
  apple/macos.bzl
  apple/providers.bzl
  apple/testing/apple_test_rules.bzl
  apple/tvos.bzl
Labels: cla: yes

#544 Rollback of split rules change.
  apple/internal/rule_factory.bzl
  apple/internal/testing/apple_test_assembler.bzl
  apple/internal/testing/apple_test_bundle_support.bzl
  apple/internal/testing/apple_test_rule_support.bzl
  apple/internal/testing/ios_rules.bzl
  apple/internal/testing/macos_rules.bzl
  apple/internal/testing/tvos_rules.bzl
  apple/ios.bzl
  apple/macos.bzl
  apple/providers.bzl
  apple/testing/apple_test_rules.bzl
  apple/tvos.bzl
Labels: cla: yes

#541 A rule to test the contents of an archive via environmental variables
  test/starlark_tests/rules/apple_verification_test.bzl
  test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template
  test/starlark_tests/verifier_scripts/archive_contents_test.sh
Labels: cla: yes

#547 Migrate dsym build checks to Starlark.
  test/ios_application_test.sh
  test/ios_ui_test_test.sh
  test/ios_unit_test_test.sh
  test/macos_application_test.sh
  test/macos_bundle_test.sh
  test/macos_quick_look_plugin_test.sh
  test/macos_ui_test_test.sh
  test/macos_unit_test_test.sh
  test/starlark_tests/apple_bundle_version_tests.bzl
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/ios_extension_tests.bzl
  test/starlark_tests/ios_imessage_application_tests.bzl
  test/starlark_tests/ios_sticker_pack_extension_tests.bzl
  test/starlark_tests/ios_ui_test_tests.bzl
  test/starlark_tests/ios_unit_test_tests.bzl
  test/starlark_tests/macos_application_tests.bzl
  test/starlark_tests/macos_bundle_tests.bzl
  test/starlark_tests/macos_quick_look_plugin_tests.bzl
  test/starlark_tests/macos_ui_test_tests.bzl
  test/starlark_tests/macos_unit_test_tests.bzl
  test/starlark_tests/rules/dsyms_test.bzl
  test/starlark_tests/tvos_application_tests.bzl
  test/starlark_tests/tvos_extension_tests.bzl
  test/starlark_tests/tvos_ui_test_tests.bzl
  test/starlark_tests/tvos_unit_test_tests.bzl
  test/starlark_tests/watchos_application_tests.bzl
  test/starlark_tests/watchos_extension_tests.bzl
  test/tvos_application_test.sh
  test/tvos_ui_test_test.sh
  test/tvos_unit_test_test.sh
Labels: cla: yes

#550 Prepare tvOS tests for test rule split.
  test/tvos_unit_test_resources_test.sh
  test/tvos_unit_test_test.sh
Labels: cla: yes

#524 Cleanup for --incompatible_restrict_named_params
  apple/internal/bundling_support.bzl
Labels: cla: no

#548 Split test rules into a bundle rule and a test rule.
  apple/internal/rule_factory.bzl
  apple/internal/testing/apple_test_assembler.bzl
  apple/internal/testing/apple_test_bundle_support.bzl
  apple/internal/testing/apple_test_rule_support.bzl
  apple/internal/testing/ios_rules.bzl
  apple/internal/testing/macos_rules.bzl
  apple/internal/testing/tvos_rules.bzl
  apple/ios.bzl
  apple/macos.bzl
  apple/providers.bzl
  apple/testing/apple_test_rules.bzl
  apple/tvos.bzl
Labels: cla: yes

#551 Add the tags attribute from the test target to the bundle target as well.
  apple/internal/testing/apple_test_assembler.bzl
Labels: cla: yes

#552 Copy over the common attributes earlier.
  apple/internal/testing/apple_test_assembler.bzl
Labels: cla: yes

#553 Fix codesigningtool.py py3 compatibility.
  tools/codesigningtool/codesigningtool.py
Labels: Import Ready, cla: yes

#555 Add platform_type to the test rules to allow Tulsi some time to migrate to AppleBundleInfo.platform_type.
  apple/internal/rule_factory.bzl
  apple/internal/testing/ios_rules.bzl
  apple/internal/testing/macos_rules.bzl
  apple/internal/testing/tvos_rules.bzl
Labels: cla: yes

#559 Handle possible empty values for --ios_simulator_device and --ios_simulator_version when invoking bazel run.
  apple/internal/run_support.bzl
  apple/internal/templates/ios_sim.template.sh
Labels: cla: yes

#561 Update xctestrunner dependency.
  apple/repositories.bzl
Labels: cla: no

#560 Expand archive_contents_test
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/ios_unit_test_tests.bzl
  test/starlark_tests/macos_application_tests.bzl
  test/starlark_tests/rules/common_verification_tests.bzl
  test/starlark_tests/tvos_application_tests.bzl
  test/starlark_tests/verifier_scripts/archive_contents_test.sh
  test/starlark_tests/verifier_scripts/resources_verifier.sh
  test/starlark_tests/watchos_application_tests.bzl
Labels: cla: yes

#563 Migrate additional_contents tests to Starlark.
  test/macos_application_test.sh
  test/macos_bundle_test.sh
  test/macos_ui_test_test.sh
  test/macos_unit_test_test.sh
  test/starlark_tests/macos_application_tests.bzl
  test/starlark_tests/macos_bundle_tests.bzl
  test/starlark_tests/macos_quick_look_plugin_tests.bzl
  test/starlark_tests/macos_ui_test_tests.bzl
  test/starlark_tests/macos_unit_test_tests.bzl
  test/starlark_tests/resources/BUILD
  test/starlark_tests/resources/additional.txt
  test/starlark_tests/resources/nested/nested.txt
  test/starlark_tests/resources/non_nested.txt
  test/starlark_tests/targets_under_test/macos/BUILD
Labels: cla: yes

#558 Add transition to macOS rules and fixes tests to account for transition changes.
  apple/internal/rule_support.bzl
Labels: cla: yes

#562 Allow archive_contents_test() to test for binary plists
  test/starlark_tests/ios_application_tests.bzl
  test/starlark_tests/rules/common_verification_tests.bzl
  test/starlark_tests/verifier_scripts/archive_contents_test.sh
Labels: cla: yes

#565 Drop some of the shard counts.
  test/BUILD
Labels: cla: yes

#556 Add missing umbrella_header documentation to ios_static_framework rule
  doc/rules-ios.md
Labels: Import Ready, cla: yes

#569 Specify maxsplit positionally instead of by keyword
  apple/internal/processor.bzl
  apple/internal/testing/apple_test_assembler.bzl
Labels: cla: yes

#570 Use positional args for rfind.
  apple/internal/utils/bundle_paths.bzl
Labels: cla: yes
